# Generated by Django 5.1.1 on 2024-09-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('strategyName', models.CharField(max_length=100)),
                ('tradesCount', models.FloatField()),
                ('worstDrawback', models.FloatField()),
                ('averagePositifTrade', models.FloatField()),
                ('averageNegativeTrade', models.FloatField()),
                ('strategyParameter', models.TextField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
        ),
        migrations.CreateModel(
            name='TradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('strategyName', models.CharField(max_length=100)),
                ('strategyData', models.TextField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('low_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProbabilitySMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('close_price', models.FloatField()),
                ('pente_SMMA20', models.FloatField()),
                ('pente_SMMA50', models.FloatField()),
                ('pente_SMMA200', models.FloatField()),
                ('Gain', models.FloatField()),
                ('tendance_SMMA20', models.CharField(max_length=50)),
                ('tendance_SMMA50', models.CharField(max_length=50)),
                ('tendance_SMMA200', models.CharField(max_length=50)),
                ('all_SMMA_increase', models.CharField(max_length=50)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyBollingerBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('BB_Lower', models.FloatField()),
                ('BB_Middle', models.FloatField()),
                ('BB_Upper', models.FloatField()),
                ('BB_Bandwidth', models.FloatField()),
                ('BB_Percent', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyDataMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('close_price', models.FloatField()),
                ('MM10', models.FloatField()),
                ('MM15', models.FloatField(blank=True, null=True)),
                ('MM20', models.FloatField(blank=True, null=True)),
                ('MM25', models.FloatField(blank=True, null=True)),
                ('MM30', models.FloatField(blank=True, null=True)),
                ('MM35', models.FloatField(blank=True, null=True)),
                ('MM40', models.FloatField(blank=True, null=True)),
                ('MM45', models.FloatField(blank=True, null=True)),
                ('MM50', models.FloatField(blank=True, null=True)),
                ('MM55', models.FloatField(blank=True, null=True)),
                ('MM60', models.FloatField(blank=True, null=True)),
                ('MM65', models.FloatField(blank=True, null=True)),
                ('MM70', models.FloatField(blank=True, null=True)),
                ('MM75', models.FloatField(blank=True, null=True)),
                ('MM80', models.FloatField(blank=True, null=True)),
                ('MM85', models.FloatField(blank=True, null=True)),
                ('MM90', models.FloatField(blank=True, null=True)),
                ('MM95', models.FloatField(blank=True, null=True)),
                ('MM100', models.FloatField(blank=True, null=True)),
                ('MM200', models.FloatField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyDataSMMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('close_price', models.FloatField()),
                ('SMMA20', models.FloatField()),
                ('SMMA50', models.FloatField(blank=True, null=True)),
                ('SMMA200', models.FloatField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyIchimoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('Ichimoku_Conversion', models.FloatField()),
                ('Ichimoku_Base', models.FloatField()),
                ('Ichimoku_LeadingA', models.FloatField()),
                ('Ichimoku_LeadingB', models.FloatField()),
                ('Ichimoku_Lagging', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyMACD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('macd', models.FloatField()),
                ('macd_signal', models.FloatField()),
                ('macd_histogram', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyRSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('rsi_7', models.FloatField()),
                ('rsi_14', models.FloatField()),
                ('rsi_21', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyStochastique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('stochastic_k', models.FloatField()),
                ('stochastic_d', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_back_app_v2.market')),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
    ]
