# Generated by Django 5.1.1 on 2024-09-23 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='strategybollingerband',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategybollingerband',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategydatamm',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategydatamm',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategydatasmma',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategydatasmma',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategyichimoku',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategyichimoku',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategymacd',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategymacd',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategyrsi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategyrsi',
            name='market',
        ),
        migrations.AlterUniqueTogether(
            name='strategystochastique',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strategystochastique',
            name='market',
        ),
        migrations.RenameField(
            model_name='tradingresult',
            old_name='strategyData',
            new_name='strategyParameter',
        ),
        migrations.AddField(
            model_name='backtest',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='buy_price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='date_end',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='date_start',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='dollars_profit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='percent_profit',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingresult',
            name='sell_price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backtest',
            name='interval_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='market',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='market',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tradingresult',
            name='interval_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingresult',
            name='market',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='backtest',
            unique_together={('market', 'interval_time', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='tradingresult',
            unique_together={('market', 'interval_time', 'date_start')},
        ),
        migrations.CreateModel(
            name='IndicatorBollingerBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('BB_Lower', models.FloatField()),
                ('BB_Middle', models.FloatField()),
                ('BB_Upper', models.FloatField()),
                ('BB_Bandwidth', models.FloatField()),
                ('BB_Percent', models.FloatField()),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorEMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('close_price', models.FloatField()),
                ('EMA20', models.FloatField()),
                ('EMA50', models.FloatField(blank=True, null=True)),
                ('EMA200', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorIchimoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('Ichimoku_Conversion', models.FloatField()),
                ('Ichimoku_Base', models.FloatField()),
                ('Ichimoku_LeadingA', models.FloatField()),
                ('Ichimoku_LeadingB', models.FloatField()),
                ('Ichimoku_Lagging', models.FloatField()),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorMACD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('macd', models.FloatField()),
                ('macd_signal', models.FloatField()),
                ('macd_histogram', models.FloatField()),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorRSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('rsi_7', models.FloatField()),
                ('rsi_14', models.FloatField()),
                ('rsi_21', models.FloatField()),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorSMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('close_price', models.FloatField()),
                ('MM10', models.FloatField()),
                ('MM15', models.FloatField(blank=True, null=True)),
                ('MM20', models.FloatField(blank=True, null=True)),
                ('MM25', models.FloatField(blank=True, null=True)),
                ('MM30', models.FloatField(blank=True, null=True)),
                ('MM35', models.FloatField(blank=True, null=True)),
                ('MM40', models.FloatField(blank=True, null=True)),
                ('MM45', models.FloatField(blank=True, null=True)),
                ('MM50', models.FloatField(blank=True, null=True)),
                ('MM55', models.FloatField(blank=True, null=True)),
                ('MM60', models.FloatField(blank=True, null=True)),
                ('MM65', models.FloatField(blank=True, null=True)),
                ('MM70', models.FloatField(blank=True, null=True)),
                ('MM75', models.FloatField(blank=True, null=True)),
                ('MM80', models.FloatField(blank=True, null=True)),
                ('MM85', models.FloatField(blank=True, null=True)),
                ('MM90', models.FloatField(blank=True, null=True)),
                ('MM95', models.FloatField(blank=True, null=True)),
                ('MM100', models.FloatField(blank=True, null=True)),
                ('MM200', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorStochastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('stochastic_k', models.FloatField()),
                ('stochastic_d', models.FloatField()),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyDataTendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('close_price', models.FloatField()),
                ('pente_SMMA20', models.FloatField()),
                ('pente_SMMA50', models.FloatField()),
                ('pente_SMMA200', models.FloatField()),
                ('tendance_SMMA20', models.CharField(max_length=50)),
                ('tendance_SMMA50', models.CharField(max_length=50)),
                ('tendance_SMMA200', models.CharField(max_length=50)),
                ('tendance_all', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('market', 'interval_time', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='ProbabilitySMMA',
        ),
        migrations.DeleteModel(
            name='StrategyBollingerBand',
        ),
        migrations.DeleteModel(
            name='StrategyDataMM',
        ),
        migrations.DeleteModel(
            name='StrategyDataSMMA',
        ),
        migrations.DeleteModel(
            name='StrategyIchimoku',
        ),
        migrations.DeleteModel(
            name='StrategyMACD',
        ),
        migrations.DeleteModel(
            name='StrategyRSI',
        ),
        migrations.DeleteModel(
            name='StrategyStochastique',
        ),
    ]
