# Generated by Django 5.1.1 on 2024-09-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0002_alter_strategybollingerband_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backtest',
        ),
        migrations.DeleteModel(
            name='IndicatorBollingerBand',
        ),
        migrations.DeleteModel(
            name='IndicatorEMA',
        ),
        migrations.DeleteModel(
            name='IndicatorIchimoku',
        ),
        migrations.DeleteModel(
            name='IndicatorMACD',
        ),
        migrations.DeleteModel(
            name='IndicatorRSI',
        ),
        migrations.DeleteModel(
            name='IndicatorSMA',
        ),
        migrations.DeleteModel(
            name='IndicatorStochastic',
        ),
        migrations.DeleteModel(
            name='StrategyDataTendance',
        ),
        migrations.DeleteModel(
            name='TradingResult',
        ),
    ]
