# Generated by Django 5.1.1 on 2024-09-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0004_backtest_indicatorbollingerband_indicatorema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorema',
            name='EMA20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorsma',
            name='MM10',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
