# Generated by Django 5.1.1 on 2024-09-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0005_alter_indicatorema_ema20_alter_indicatorsma_mm10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='pente_SMMA20',
            new_name='pente_EMA20',
        ),
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='pente_SMMA200',
            new_name='pente_EMA200',
        ),
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='pente_SMMA50',
            new_name='pente_EMA50',
        ),
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='tendance_SMMA20',
            new_name='tendance_EMA20',
        ),
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='tendance_SMMA200',
            new_name='tendance_EMA200',
        ),
        migrations.RenameField(
            model_name='strategydatatendance',
            old_name='tendance_SMMA50',
            new_name='tendance_EMA50',
        ),
    ]
