# Generated by Django 5.1.1 on 2024-09-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0006_rename_pente_smma20_strategydatatendance_pente_ema20_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backtest',
            unique_together={('market', 'interval_time')},
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='date',
        ),
    ]
