# Generated by Django 5.1.1 on 2024-10-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0007_alter_backtest_unique_together_remove_backtest_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradingresult',
            unique_together={('market', 'interval_time', 'date_start', 'strategyName')},
        ),
    ]
