# Generated by Django 5.1.1 on 2024-10-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0008_alter_tradingresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorbollingerband',
            name='close_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorichimoku',
            name='close_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatormacd',
            name='close_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorrsi',
            name='close_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorstochastic',
            name='close_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
