# Generated by Django 5.1.1 on 2024-10-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0009_indicatorbollingerband_close_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backtest',
            unique_together={('market', 'interval_time', 'strategyName')},
        ),
    ]
