# Generated by Django 5.1.1 on 2024-10-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_back_app_v2', '0010_alter_backtest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStrategyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interval_time', models.CharField(max_length=10)),
                ('strategy_tendance_color', models.CharField(max_length=10)),
                ('strategy_macd_color', models.CharField(max_length=10)),
                ('strategy_ichimoku_color', models.CharField(max_length=10)),
                ('strategy_2sma_color', models.CharField(max_length=10)),
                ('strategy_bb_color', models.CharField(max_length=10)),
                ('strategy_rsi_color', models.CharField(max_length=10)),
                ('strategy_stochastic_color', models.CharField(max_length=10)),
            ],
        ),
    ]
