PRAGMA foreign_keys = 0;

CREATE TABLE StrategyDataEMA (
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT,
    date   TEXT,
    EMA10  NUMERIC,
    EMA15  NUMERIC,
    EMA20  NUMERIC,
    EMA25  NUMERIC,
    EMA30  NUMERIC,
    EMA35  NUMERIC,
    EMA40  NUMERIC,
    EMA45  NUMERIC,
    EMA50  NUMERIC,
    EMA55  NUMERIC,
    EMA60  NUMERIC,
    EMA65  NUMERIC,
    EMA70  NUMERIC,
    EMA75  NUMERIC,
    EMA80  NUMERIC,
    EMA85  NUMERIC,
    EMA90  NUMERIC,
    EMA95  NUMERIC,
    EMA100 NUMERIC,
    close_price NUMERIC
);

PRAGMA foreign_keys = 1;