name: Build and Push Images

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        working-directory: Back/trading_back_v2
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/trading/trading-back:latest .
          docker push ghcr.io/${{ github.repository_owner }}/trading/trading-back:latest
    
      - name: Build and push API image
        working-directory: API_trading
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/trading/trading-api:latest .
          docker push ghcr.io/${{ github.repository_owner }}/trading/trading-api:latest
      
      - name: Build and push Frontend image
        working-directory: Front/trading_front
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/trading/trading-front:latest .
          docker push ghcr.io/${{ github.repository_owner }}/trading/trading-front:latest