name: Deploy Trading Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Mise à jour de la version de checkout pour utiliser Node 20
      - name: Checkout code
        uses: actions/checkout@v4  # Passage de v2 à v4

      # Vérification de la structure du projet
      - name: List project structure
        run: ls -la
      
      # Test de construction des services avec docker-compose
      - name: Test docker-compose build
        run: |
          if [ -f "docker-compose.yml" ]; then
            docker-compose build
          else
            echo "docker-compose.yml not found"
            exit 1
          fi

      # Transfert des fichiers via SCP
      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7  # Ajout d'une version spécifique
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          source: "."
          target: "~/trading_app"
          rm: true
          strip_components: 0

      # Déploiement sur la VM Oracle
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.3  # Ajout d'une version spécifique
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            cd ~/trading_app
            
            if [ -f "docker-compose.yml" ]; then
              docker-compose down || true
              docker-compose up -d --build
              docker ps
              docker image prune -f
            else
              echo "docker-compose.yml not found in ~/trading_app"
              ls -la
              exit 1
            fi
