name: Deploy Trading Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Installation de Docker et Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          source: |
            .
            !.git
          target: "~/trading_app"
          rm: true
          debug: true

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_VM_SSH_KEY }}
          script: |
            cd ~/trading_app
            
            # Installer Docker et Docker Compose si nécessaire
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose
            fi

            # Charger les variables d'environnement
            export $(cat .env | xargs)

            # Arrêter et supprimer les conteneurs existants
            docker-compose down --volumes

            # Reconstruire et démarrer les services
            docker-compose up -d --build

            # Vérifier le statut des conteneurs
            docker-compose ps